spring:
  application:
    name: futeApi
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

api:
  x-apisports-key: ${API_FOOTBALL_KEY}

gemini:
  api-key: ${GOOGLE_AI_KEY}
  model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com
